# Generated by Django 3.1.4 on 2020-12-27 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0004_remove_project_current_process'),
        ('scripts', '0004_auto_20201227_2220'),
    ]

    operations = [
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clam_id', models.CharField(default=None, max_length=256, null=True)),
                ('status', models.IntegerField(choices=[(0, 'Created'), (1, 'Uploading files to CLAM'), (2, 'Running'), (3, 'Waiting for download from CLAM'), (4, 'Downloading files from CLAM'), (5, 'Finished'), (-1, 'Error'), (-2, 'Error while downloading files from CLAM')], default=0)),
                ('folder', models.FilePathField(allow_files=False, allow_folders=True)),
                ('script', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scripts.script')),
            ],
            options={
                'verbose_name_plural': 'Processes',
            },
        ),
        migrations.CreateModel(
            name='ParameterSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=1024)),
                ('base_parameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scripts.baseparameter')),
            ],
        ),
        migrations.CreateModel(
            name='LogMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(null=True)),
                ('message', models.CharField(max_length=16384)),
                ('index', models.PositiveIntegerField()),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='processes.process')),
            ],
        ),
        migrations.CreateModel(
            name='FileSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.file')),
                ('input_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scripts.inputtemplate')),
            ],
        ),
    ]
