# Generated by Django 3.1.4 on 2020-12-28 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_remove_project_current_process'),
        ('scripts', '0004_auto_20201227_2220'),
        ('processes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametersetting',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='projects.project'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='filesetting',
            name='input_template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_settings', to='scripts.inputtemplate'),
        ),
        migrations.AlterField(
            model_name='parametersetting',
            name='base_parameter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameter_settings', to='scripts.baseparameter'),
        ),
        migrations.AlterUniqueTogether(
            name='parametersetting',
            unique_together={('base_parameter', 'project')},
        ),
    ]
