# Generated by Django 3.1.5 on 2021-01-20 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0004_auto_20210120_1353'),
        ('projects', '0002_auto_20210120_1353'),
        ('processes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filepreset',
            name='input_template',
            field=models.ForeignKey(help_text='The Input template for which to register the File Preset. When automatic configuration of File Settings is being ran by a User, all File Presets of an Input template will try to match files in the corresponding Project. If one matches it will be created as a File Setting.', on_delete=django.db.models.deletion.CASCADE, to='scripts.inputtemplate'),
        ),
        migrations.AlterField(
            model_name='filepreset',
            name='name',
            field=models.CharField(help_text='The name of the File Preset, only used for distinguishing different File Presets', max_length=1024),
        ),
        migrations.AlterField(
            model_name='filepreset',
            name='regex',
            field=models.CharField(help_text='The regular expression to use when matching file names of a Project.', max_length=1024),
        ),
        migrations.AlterField(
            model_name='filesetting',
            name='file',
            field=models.ForeignKey(help_text='The file for which this file setting is specified.', on_delete=django.db.models.deletion.CASCADE, to='projects.file'),
        ),
        migrations.AlterField(
            model_name='filesetting',
            name='input_template',
            field=models.ForeignKey(help_text='The Input Template to register the File Setting for.', on_delete=django.db.models.deletion.CASCADE, related_name='file_settings', to='scripts.inputtemplate'),
        ),
        migrations.AlterField(
            model_name='logmessage',
            name='index',
            field=models.PositiveIntegerField(help_text='The index of the log message. Log messages will be sorted on their index.'),
        ),
        migrations.AlterField(
            model_name='logmessage',
            name='message',
            field=models.CharField(help_text='The log message.', max_length=16384),
        ),
        migrations.AlterField(
            model_name='logmessage',
            name='process',
            field=models.ForeignKey(help_text='The process for which this log message is.', on_delete=django.db.models.deletion.CASCADE, to='processes.process'),
        ),
        migrations.AlterField(
            model_name='logmessage',
            name='time',
            field=models.DateTimeField(help_text='The time of the log message.', null=True),
        ),
        migrations.AlterField(
            model_name='parametersetting',
            name='_value',
            field=models.CharField(help_text='The value of the Parameter Setting in string format.', max_length=1024),
        ),
        migrations.AlterField(
            model_name='parametersetting',
            name='base_parameter',
            field=models.ForeignKey(help_text='The Base Parameter to register the Parameter Setting for.', on_delete=django.db.models.deletion.CASCADE, related_name='parameter_setting', to='scripts.baseparameter'),
        ),
        migrations.AlterField(
            model_name='parametersetting',
            name='project',
            field=models.ForeignKey(help_text='The Project for which to register the Parameter Setting.', on_delete=django.db.models.deletion.CASCADE, to='projects.project'),
        ),
        migrations.AlterField(
            model_name='process',
            name='clam_id',
            field=models.CharField(default=None, help_text='The CLAM Project name that is being used on the CLAM server to run this Process.', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='process',
            name='created',
            field=models.DateTimeField(auto_now_add=True, help_text='The time that this Process was created.'),
        ),
        migrations.AlterField(
            model_name='process',
            name='folder',
            field=models.FilePathField(allow_files=False, allow_folders=True, help_text='The folder to write all output files of this Process to.', path='media/processes'),
        ),
        migrations.AlterField(
            model_name='process',
            name='project',
            field=models.ForeignKey(help_text='The Project for which this Process isbeing ran.', on_delete=django.db.models.deletion.CASCADE, to='projects.project'),
        ),
        migrations.AlterField(
            model_name='process',
            name='script',
            field=models.ForeignKey(help_text='The Script for which this Process is being ran.', on_delete=django.db.models.deletion.CASCADE, to='scripts.script'),
        ),
        migrations.AlterField(
            model_name='process',
            name='status',
            field=models.IntegerField(choices=[(0, 'Created'), (1, 'Uploading files to CLAM'), (2, 'Running'), (3, 'Waiting for download from CLAM'), (4, 'Downloading files from CLAM'), (5, 'Finished'), (-1, 'Error'), (-2, 'Error while downloading files from CLAM')], default=0, help_text='The current status of this Process. This will be automatically mirrored with the CLAM server.'),
        ),
    ]
