# Generated by Django 3.1.5 on 2021-01-26 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0005_auto_20210126_1349'),
        ('processes', '0002_auto_20210120_1353'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filepreset',
            name='name',
        ),
        migrations.CreateModel(
            name='PreferableFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regex', models.CharField(help_text='The regular expression to use when matching file names of a Project.', max_length=1024)),
                ('input_template', models.ForeignKey(help_text='The Input template for which to register the File list regular expression. Files that match the regular expression are shown in theProcess configuration window under this input template.', on_delete=django.db.models.deletion.CASCADE, to='scripts.inputtemplate')),
            ],
        ),
    ]
