# Generated by Django 3.1.4 on 2021-01-01 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0003_auto_20210101_1745'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parametersetting',
            old_name='value',
            new_name='_value',
        ),
    ]
