# Generated by Django 3.1.4 on 2021-01-03 11:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0004_auto_20210101_1751'),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
