# Generated by Django 3.1.4 on 2021-01-04 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0007_outputtemplate_script'),
        ('processes', '0005_process_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilePreset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
                ('regex', models.CharField(max_length=1024)),
                ('script', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scripts.inputtemplate')),
            ],
        ),
    ]
