# Generated by Django 3.1.4 on 2021-01-04 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0006_filepreset'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filepreset',
            old_name='script',
            new_name='input_template',
        ),
    ]
