# Generated by Django 3.1.4 on 2020-12-26 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('scripts', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='project',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='project',
            name='current_process',
        ),
        migrations.RemoveField(
            model_name='project',
            name='pipeline',
        ),
        migrations.RemoveField(
            model_name='project',
            name='user',
        ),
        migrations.RenameField(
            model_name='choiceparameter',
            old_name='value',
            new_name='_value',
        ),
        migrations.RemoveField(
            model_name='baseparameter',
            name='preset',
        ),
        migrations.RemoveField(
            model_name='baseparameter',
            name='type',
        ),
        migrations.RemoveField(
            model_name='booleanparameter',
            name='base',
        ),
        migrations.RemoveField(
            model_name='choiceparameter',
            name='base',
        ),
        migrations.RemoveField(
            model_name='floatparameter',
            name='base',
        ),
        migrations.RemoveField(
            model_name='integerparameter',
            name='base',
        ),
        migrations.RemoveField(
            model_name='staticparameter',
            name='base',
        ),
        migrations.RemoveField(
            model_name='stringparameter',
            name='base',
        ),
        migrations.RemoveField(
            model_name='textparameter',
            name='base',
        ),
        migrations.AddField(
            model_name='baseparameter',
            name='content_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='baseparameter',
            name='object_id',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='baseparameter',
            name='corresponding_script',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='scripts.script'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='choice',
            name='corresponding_choice_parameter',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='scripts.choiceparameter'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inputtemplate',
            name='corresponding_profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='scripts.profile'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='process',
            name='script',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='scripts.script'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='script',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='scripts.script'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Pipeline',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
    ]
