# Generated by Django 3.1.4 on 2020-12-26 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0002_auto_20201226_1733'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choiceparameter',
            old_name='_value',
            new_name='value',
        ),
        migrations.RemoveField(
            model_name='baseparameter',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='baseparameter',
            name='object_id',
        ),
        migrations.AddField(
            model_name='baseparameter',
            name='preset',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='baseparameter',
            name='type',
            field=models.IntegerField(choices=[(0, 'Boolean'), (1, 'Static'), (2, 'String'), (3, 'Choice'), (4, 'Text'), (5, 'Integer'), (6, 'Float')], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booleanparameter',
            name='base',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='scripts.baseparameter'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='choiceparameter',
            name='base',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='scripts.baseparameter'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='floatparameter',
            name='base',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='scripts.baseparameter'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='integerparameter',
            name='base',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='scripts.baseparameter'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staticparameter',
            name='base',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='scripts.baseparameter'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stringparameter',
            name='base',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='scripts.baseparameter'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='textparameter',
            name='base',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='scripts.baseparameter'),
            preserve_default=False,
        ),
    ]
