# Generated by Django 3.1.4 on 2020-12-27 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0003_auto_20201226_2008'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='process',
            name='script',
        ),
        migrations.AlterField(
            model_name='baseparameter',
            name='corresponding_script',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='scripts.script'),
        ),
        migrations.AlterField(
            model_name='inputtemplate',
            name='corresponding_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='input_templates', to='scripts.profile'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='script',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to='scripts.script'),
        ),
        migrations.DeleteModel(
            name='LogMessage',
        ),
        migrations.DeleteModel(
            name='Process',
        ),
    ]
