# Generated by Django 3.1.4 on 2021-01-01 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0004_auto_20201227_2220'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='baseparameter',
            unique_together={('name', 'corresponding_script')},
        ),
    ]
