# Generated by Django 3.1.5 on 2021-01-26 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0004_auto_20210120_1353'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outputtemplate',
            name='name',
        ),
        migrations.AddField(
            model_name='profile',
            name='name',
            field=models.CharField(blank=True, help_text='Optional name, will be showed instead of profile number.', max_length=1024, null=True),
        ),
    ]
