# Generated by Django 3.1.4 on 2021-01-02 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0006_outputtemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='outputtemplate',
            name='script',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='scripts.script'),
            preserve_default=False,
        ),
    ]
