# Generated by Django 3.1.4 on 2020-12-26 16:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import projects.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pipelines', '0001_initial'),
        ('scripts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('folder', models.FilePathField(allow_files=False, allow_folders=True, path="")),
                ('current_process', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scripts.process')),
                ('pipeline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pipelines.pipeline')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': [('access_project', 'Access project')],
                'unique_together': {('name', 'user')},
            },
        ),
    ]
