# Generated by Django 3.1.4 on 2020-12-26 22:30

from django.db import migrations, models
import projects.models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20201226_2233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(unique=True, upload_to=projects.models.project_folder_path),
        ),
    ]
