# Generated by Django 3.1.5 on 2021-01-06 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scripts', '0003_auto_20210106_1056'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pipeline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('fa_script', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fa_script', to='scripts.script')),
                ('g2p_script', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='g2p_script', to='scripts.script')),
            ],
        ),
    ]
