# Generated by Django 3.1.5 on 2021-01-20 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0004_auto_20210120_1353'),
        ('pipelines', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pipeline',
            name='fa_script',
            field=models.ForeignKey(help_text='The Forced Alignment Script to use for the Forced Alignment part of the Pipeline.', on_delete=django.db.models.deletion.PROTECT, related_name='fa_script', to='scripts.script'),
        ),
        migrations.AlterField(
            model_name='pipeline',
            name='g2p_script',
            field=models.ForeignKey(help_text='The Grapheme to Phoneme Script to use for the Grapheme to Phoneme part of the Pipeline.', on_delete=django.db.models.deletion.PROTECT, related_name='g2p_script', to='scripts.script'),
        ),
        migrations.AlterField(
            model_name='pipeline',
            name='name',
            field=models.CharField(help_text='The name of the Pipeline to appear to users when creating a new Project.', max_length=512),
        ),
    ]
