# Generated by Django 3.1.5 on 2021-01-26 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pipelines', '0002_auto_20210120_1353'),
    ]

    operations = [
        migrations.CreateModel(
            name='DictionaryFileFormat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regex', models.CharField(help_text='The regular expression to use when matching file names.', max_length=1024)),
                ('pipeline', models.ForeignKey(help_text='The Pipeline for which to register the Dictionary File Format. Files that match the regular expression are shown in theCheck Dictionary screen.', on_delete=django.db.models.deletion.CASCADE, to='pipelines.pipeline')),
            ],
        ),
    ]
