---

name: "Testing"
on: "pull_request"

jobs:
  test:
    name: "Testing"
    runs-on: "ubuntu-latest"
    steps:

    - name: "Checkout the repository"
      uses: "actions/checkout@v1"

    - name: "Setup Python"
      uses: "actions/setup-python@v1"
      with:
        python-version: '3.7'

    - name: "Install Poetry"
      run: |
        python -m pip install --upgrade pip
        python -m pip install poetry

    - name: "Restore any cached Poetry dependencies"
      uses: actions/cache@v1
      with:
        path: ~/.cache/pypoetry/virtualenvs
        key: ${{ runner.os }}-poetry-${{ hashFiles('poetry.lock') }}
        restore-keys: |
          ${{ runner.os }}-poetry-
          
    - name: "Install any new dependencies"
      run: poetry install
      if: steps.cache.outputs.cache-hit != 'true'

    - name: "Test migrations"
      run: |
        poetry run python equestria/manage.py makemigrations --no-input --check --dry-run

    - name: Check server
      run: |
        poetry run python3 equestria/manage.py check

    - name: "Run Django tests using Coverage"
      run: "MOZ_HEADLESS=1 poetry run coverage run equestria/manage.py test equestria/"

    - name: "Check Coverage report"
      run: "poetry run coverage report"

    - name: "Generate a coverage xml"
      run: "poetry run coverage xml"
